language: node_js
node_js:
  - "14.17"

before_install:
  - npm i -g npm@version-number

addons:
  chrome: stable

cache:
  npm: false

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI